name: Build and Test
on:
  push:
    branches:
      - develop

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Installation des dépendances Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Exécution des tests Python
      - name: Run Python tests
        run: |
          pytest